[mypy]
python_version = 3.12
strict = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unreachable = True
no_implicit_optional = True
show_error_codes = True
plugins = pydantic.mypy

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True

[mypy-alembic.*]
ignore_missing_imports = True

[mypy-ulid.*]
ignore_missing_imports = True

[mypy-structlog.*]
ignore_missing_imports = True

[mypy-packages.shared.migrations.*]
ignore_errors = True

[mypy-mistune.*]
ignore_missing_imports = True

[mypy-frontmatter.*]
ignore_missing_imports = True

[mypy-pygit2.*]
ignore_missing_imports = True

[mypy-prance.*]
ignore_missing_imports = True

[mypy-openapi_spec_validator.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-moto.*]
ignore_missing_imports = True

[mypy-respx.*]
ignore_missing_imports = True
