"""EventBridge Scheduler integration.

The scheduler fires an SQS message with a refresh ``Job`` body on a cron.
The target is a pre-provisioned SQS queue + role; both ARNs come from env
(``DOC_SEARCH_SCHEDULER_TARGET_ARN``, ``DOC_SEARCH_SCHEDULER_ROLE_ARN``).

When the ARNs are missing we no-op so dev stacks don't require LocalStack
Scheduler. Callers can detect this via :meth:`is_enabled`.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import Any

from doc_search_shared.ids import new_ulid, parse_library_id
from doc_search_shared.models import Job, JobSource
from doc_search_shared.settings import Settings


def _safe_name(library_id: str) -> str:
    """EventBridge Scheduler names allow ``[0-9A-Za-z._-]`` up to 64 chars."""
    parse_library_id(library_id)  # validate
    return "ds-" + library_id.lstrip("/").replace("/", "-").replace(".", "_")[:60]


class SchedulerClient:
    def __init__(self, *, scheduler: Any, settings: Settings) -> None:
        self._scheduler = scheduler
        self._settings = settings

    def is_enabled(self) -> bool:
        s = self._settings
        return bool(s.scheduler_role_arn and s.scheduler_target_arn)

    def upsert_refresh_schedule(
        self,
        *,
        library_id: str,
        version: str | None,
        source: JobSource,
        schedule_expression: str | None = None,
    ) -> str | None:
        """Create or update the refresh schedule for a library.

        Returns the schedule name, or ``None`` if the scheduler is not
        configured (dev mode).
        """
        if not self.is_enabled():
            return None

        s = self._settings
        name = _safe_name(library_id)
        expression = schedule_expression or s.scheduler_default_cron

        # The Input is the pre-rendered Job body the worker will receive.
        # job_id is regenerated by the scheduler per firing in prod via a
        # wrapper Lambda; for now we ship a stable id and let the worker
        # treat duplicates as idempotent (content-hash short-circuits).
        body = Job(
            job_id=new_ulid(),
            library_id=library_id,
            version=version,
            source=source,
            mode="incremental",
            profile="light",
            created_at=datetime.now(UTC),
        ).model_dump_json()

        target = {
            "Arn": s.scheduler_target_arn,
            "RoleArn": s.scheduler_role_arn,
            "Input": body,
            "SqsParameters": {"MessageGroupId": library_id},
        }
        params: dict[str, Any] = {
            "Name": name,
            "GroupName": s.scheduler_group_name,
            "ScheduleExpression": expression,
            "FlexibleTimeWindow": {"Mode": "OFF"},
            "Target": target,
            "State": "ENABLED",
        }

        try:
            self._scheduler.create_schedule(**params)
        except self._scheduler.exceptions.ConflictException:
            self._scheduler.update_schedule(**params)
        return name

    def delete_refresh_schedule(self, library_id: str) -> None:
        if not self.is_enabled():
            return
        name = _safe_name(library_id)
        try:
            self._scheduler.delete_schedule(
                Name=name,
                GroupName=self._settings.scheduler_group_name,
            )
        except self._scheduler.exceptions.ResourceNotFoundException:
            return


def render_refresh_input(job: Job) -> str:
    """JSON-encode the Job body the way EventBridge Scheduler expects."""
    return json.dumps(job.model_dump(mode="json"))


__all__ = ["SchedulerClient", "render_refresh_input"]
